# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/{{cookiecutter.project_name}}"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/{{cookiecutter.project_name}}"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/{{cookiecutter.project_name}}/src/frontend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/{{cookiecutter.project_name}}"
    schedule:
      interval: "weekly"
