version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./src:/app/src
      - ./log:/app/log
    env_file:
      - .env
    depends_on:
      - db
      - cache

  db:
    image: postgres:15-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB={{ cookiecutter.project_slug }}
      - POSTGRES_USER={{ cookiecutter.project_slug }}
      - POSTGRES_PASSWORD=abc123

  cache:
    image: memcached:1.6-alpine

volumes:
  postgres-data:
